version: "3.9"

services:
    app:
        build: .
        image: jacoblincool/tiktoken-calculator
        ports:
            - "7860:7860"
        environment:
            GRADIO_SERVER_NAME: "0.0.0.0"
