name: Sync to Hugging Face Spaces

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    sync-to-spaces:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  lfs: true

            - name: Sync to Hugging Face Spaces
              uses: JacobLinCool/huggingface-sync@v1
              with:
                  github: ${{ secrets.GITHUB_TOKEN }}
                  user: jacoblincool
                  space: tiktoken-calculator
                  token: ${{ secrets.HF_TOKEN }}
                  emoji: 🤗
                  colorFrom: yellow
                  colorTo: orange
                  sdk: gradio
                  app_file: app.py
                  python_version: 3.11
                  pinned: false
